apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: todo
        image: stormbreaker2023/todo-app:41
        ports:
        - containerPort: 8000
